---
script: "#./script.pf"
id: "2X37om"
name: "06.Remove All Security"
configurationVariable: []
inputFiles:
  singleInvoiceEncrypted.pdf:
    fileName: "singleInvoiceEncrypted.pdf"
    relativePath: "input/singleInvoiceEncrypted.pdf"
    size: 17893
resources:
  pdffiddlerWithPassword.pfx:
    fileName: "pdffiddlerWithPassword.pfx"
    relativePath: "resource/pdffiddlerWithPassword.pfx"
    size: 2645
imgUrl: "#./image"
keywords: "Remove All Security"
headline: "Remove All Security"
