---
script: "#./script.pf"
id: "2X37om"
name: "06.Remove All Security"
configurationVariable: []
inputFiles:
  singleInvoiceEncrypted.pdf:
    fileName: "singleInvoiceEncrypted.pdf"
    relativePath: "input/singleInvoiceEncrypted.pdf"
    size: 17893
resources:
  pdffiddlerWithPassword.pfx:
    fileName: "pdffiddlerWithPassword.pfx"
    relativePath: "resource/pdffiddlerWithPassword.pfx"
    size: 2645
imgUrl: "#./image"
keywords: "Remove All Security From PDF, Remove Password"
headline: "Remove All Security From PDF"
description: "Remove any security such as password, encryption etc.. from PDF using PDFFiddler Playground"
